---
name: cmpsc-101-fall-2018-inclass
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/main:
    java:
        inclass/IncorrectSwap.java:
            --count 48
            --single 6 --language Java
            --multi 3 --language Java
            --fragment "println(" --count 6 --exact
src/main:
    java:
        inclass/DivideByZero.java:
            --count 90
            --single 20 --language Java
            --multi 5 --language Java
            --fragment "println(" --count 16 --exact
writing/coveros.md:
    mdl
    proselint
    --paragraphs 1 --exact
    --words 100
